<a href="https://colab.research.google.com/github/sumtzehern/Deep-learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch fundamental

Notes: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.1.0+cu121'

## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.tensor()` --> https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# deimeniosn of a tensor
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# dimention is one when there is only 1 []

vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 8]])

MATRIX

tensor([[7, 8],
        [9, 8]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([9, 8])

In [ ]:
MATRIX[1][0] = 90
MATRIX

tensor([[ 7,  8],
        [90,  8]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important beacause the way many neural networks learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

` Starts with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Creatae a random tensor of size(3, 4)

random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.9725, 0.9267, 0.7204, 0.4189],
        [0.2443, 0.3476, 0.0750, 0.3571],
        [0.7859, 0.1671, 0.7189, 0.0773]])

In [ ]:
random_tensor.ndim


2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensors of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensors of all ones
one = torch.ones((3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

### Creating a range of tensors-like

In [ ]:
# Use torch.range() if get depreciate message use torch.range()

one_to_100 = torch.arange(start=1, end=100, step=6)
one_to_100


tensor([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [ ]:
# Create tensor like zeros
zeros_100 = torch.zeros_like(input=one_to_100)
zeros_100


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### [Tensor datatypes](https://pytorch.org/docs/stable/tensors.html)

**Notes:** Tensor datatype is one of the big 3 errors will run into with pyTorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float64)
                               device=None, # What device is tensor on
                               requires_grad=False) # whether or not to track gradient
float_32_tensor

tensor([3., 6., 9.])

float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (attribute)

* Tensors not right datatype - to do get datatype from a tensor, use `tensor.dype`
* Tensors not right shape - get shape from a tensor, use `tensor.shape`
* Tensors not on right device - get device from a tensor, use `tensor.device`

In [ ]:
# Create a tensor
rand_tensor = torch.rand(4,4)
rand_tensor

tensor([[0.8681, 0.8335, 0.4419, 0.2799],
        [0.1804, 0.4299, 0.5578, 0.5905],
        [0.8915, 0.2129, 0.7778, 0.9285],
        [0.5645, 0.9300, 0.6425, 0.6196]])

In [ ]:
# Find out details about some details
print(rand_tensor)
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Shape/Size of tensor: {rand_tensor.shape}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.8681, 0.8335, 0.4419, 0.2799],
        [0.1804, 0.4299, 0.5578, 0.5905],
        [0.8915, 0.2129, 0.7778, 0.9285],
        [0.5645, 0.9300, 0.6425, 0.6196]])
Datatype of tensor: torch.float32
Shape/Size of tensor: torch.Size([4, 4])
Device tensor is on: cpu


### Manipulating Tensors( tensor operations )

Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [ ]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor.add(tensor + 1)


tensor([3, 5, 7])

### Matric Multiplication

Two main ways of perform

1. Element wise
2. Matrix wise (dot product)

More info on multiplying matrices -
https://www.mathsisfun.com/algebra/matrix-multiplying.html

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the - shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- (`3, 2) @ (2, 3)` -> (`3, 3)`


Note: "@" in Python is the symbol for matrix multiplication.

In [ ]:
# Element
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Dot product
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# also matmul

tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 425 µs, sys: 0 ns, total: 425 µs
Wall time: 675 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 88.9 µs


tensor(14)

### One of the most common erros in deep learning: shape errors

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

To fix our tensor shape issues, we can manipuate the shape of one of our tensors using ***transpose***

A ***transpose*** switches the axes of diension of giving tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape # rearange the dimension

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Practice transposed

a = torch.tensor([  [1, 2],
                    [3, 4],
                    [6, 5],
                    [10, 20]])

b = torch.tensor([  [1, 2],
                    [3, 4],
                    [6, 5],
                    [10, 20]])

a.shape, b.shape

(torch.Size([4, 2]), torch.Size([4, 2]))

In [ ]:

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {a.shape}, tensor_B = {b.shape}\n")
print(f"New shapes: tensor_A = {a.shape} (same as above), tensor_B.T = {b.T.shape}\n")
print(f"Multiplying: {a.shape} * {b.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(a, b.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([4, 2]), tensor_B = torch.Size([4, 2])

New shapes: tensor_A = torch.Size([4, 2]) (same as above), tensor_B.T = torch.Size([2, 4])

Multiplying: torch.Size([4, 2]) * torch.Size([2, 4]) <- inner dimensions match

Output:

tensor([[  5,  11,  16,  50],
        [ 11,  25,  38, 110],
        [ 16,  38,  61, 160],
        [ 50, 110, 160, 500]])

Output shape: torch.Size([4, 4])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Createa tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - the torch.mean() function requires a tensor of dtype float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position of the min value
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position of the max value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* ***Reshaping*** - reshapes an input tensor to a defined shape
* ***View*** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* ***Stacking*** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* ***Squeeze*** - removes all `1` dimensions from a tensor
* ***Unqueeze*** - add a `1` to a target tensor
* ***Permute*** Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# Create a tensor in arange of 1. anto 10.

import torch
x = torch.arange(1, 10)
x, x.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add adn extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# torch.squeeze() - Remove all single dimensions from a target tensor
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeeze = x_reshaped.squeeze()

In [ ]:
# remove single dimention
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# torch.unsqueeze() - add a single dimensions to a tager tensor at a specific dim

print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}\n")

# Add an extra dimension
print(f"New tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")



Previous target: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in a specifc order

# common in image
x_ori = torch.rand(224, 123, 3) # [height, width, color_channels]

# Permute the ori tensor to rearrange the axis (or dim) order
x_permuted = x_ori.permute(2, 0, 1) # shift axis 0 -> 1 1->2 2-> 0

print(f"Previous shape: {x_ori.shape}")
print(f"New Shape: {x_permuted.shape}") # [color_channels, height, width]


Previous shape: torch.Size([224, 123, 3])
New Shape: torch.Size([3, 224, 123])


In [ ]:
x_ori[0, 0, 0] = 6666
x_ori[0, 0, 0], x_permuted[0, 0, 0 ]

(tensor(6666.), tensor(6666.))

## Indexing( selecting data from tensors)

indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on first tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index the most indder bracket
x[0][2][2]

tensor(9)

In [ ]:
# You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all value of 0th and 1st dimension but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dim but only the 1 index value of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, : ]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0][2][2]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Index of  1 4 7
x[:, :, 0]

tensor([[1, 4, 7]])

## Pytorch tensors & Numpy

Numpy : scientific Python numerical computing library

* Data in NumPy, want in PyTorch tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor --> Numpy -> `torch.Tensor.numpy()`

In [ ]:
torch.arange(1.0, 8.0).dtype # default PyTorch dtype

torch.float32

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor # default dtype for NumPY is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In short how neural network learns:

`starts with random nuber -> tensor operations -> update random numbers to try and make them better representation of the data -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a ***random seed***.

Essentialy what the random seed does is "flavour" the randomness.

https://pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed#:~:text=A%20random%20seed%20(or%20seed,not%20need%20to%20be%20random.

In [ ]:
import torch

# Create 2 random tensors
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A)
print(random_B)
print(random_A == random_B) # they are not equal

tensor([[0.8608, 0.8952, 0.9270, 0.0611],
        [0.1534, 0.7113, 0.9133, 0.9886],
        [0.3348, 0.1401, 0.1626, 0.1517]])
tensor([[0.5166, 0.3291, 0.8442, 0.6376],
        [0.2645, 0.1450, 0.9645, 0.3515],
        [0.0804, 0.6335, 0.2759, 0.1172]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# To make it random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C == random_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

GPUs: Faster computation on numbers (SUDA + NVDIA HARDWARE + PyTorch)

### 1. Getting a GPU
 * Own GPU
 * cloud computing
 * google Colab

In [ ]:
!nvidia-smi

Fri Mar  8 20:40:41 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

2. ### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "gpu"
device

'cuda'

For PyTorch since it's capable of running on GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g: run on GPU if available, else default to CPU

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create tensor (defaul on CPU )
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available )
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [ ]:
# IF tensor in on GPU, can't transform it to Numpy
tensor_back_cpu = tensor_gpu.cpu().numpy()
tensor_back_cpu

array([1, 2, 3])

## Exercises & Extra-curriculumn

Exercises for this notebook:
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises